### ISSUE TITLE
pnull is wrong

### ISSUE THREAD

**Issue by CPernet** [CPernet/ReproducibleQuantitativeDataScience#1]
I'm afraid my lack of python skills is flagrant here ... in the notebook https://github.com/CPernet/ReproducibleQuantitativeDataScience/blob/main/p_values/p_values.ipynb there is an error somewhere around -- pnull are not what they are supposed to be (we should get mean 5% as in the [Matlab code](https://github.com/CPernet/ReproducibleQuantitativeDataScience/blob/main/p_values/p_values.m#L22))

```
# Calculate p-values from statsb
# Reshape statsb to a 2D array
statsb = statsb.reshape(100, -1)

# Calculate p-values for each value in statsb
pnull = np.zeros(statsb.shape)
for i in range(statsb.shape[0]):
    pnull[i] = 2 * np.minimum(statsb[i] > t_stat, statsb[i] < t_sta
```t)

**Comment by robertoostenveld** [comment]
... as if I am such a Python guru ;-)

I will give it a try.

**Comment by CPernet** [comment]
i was more counting on @melanieganz TBH

**Comment by robertoostenveld** [comment]
the line 
```
pnull[i] = 2 * np.minimum(statsb[i] > t_stat, statsb[i] < t_stat)
```
takes the minimum of two Boolean vectors, one of which is always false. So it always results in zero. I believe it goes wrong on line

```
statsb = ttest_ind(Xb[resamples], Yb[resamples])[0]  # compute 10000 t-tests
```

which I would replace with 

```
statsb, pnull = ttest_ind(Xb[resamples], Yb[resamples])  # compute 10000 t-tests
```

**Comment by CPernet** [comment]
indeed - solved thx, now the pnull distribution is uniform-ish as expected 
https://github.com/CPernet/ReproducibleQuantitativeDataScience/blob/main/p_values/p_values.ipynb
